apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql # mysql component service name
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  labels:
    component: backend
    tier: backend
    project: expense

spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      tier: backend
      project: expense

  template:
    metadata:

      labels:
        component: backend
        tier: backend
        project: expense
      
    spec:
      containers:
      - name: mysql
        image: pudviks/mysql:1.0
        envFrom:
        - configMapRef:
            name: backend


---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: backend
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port